# Laboratorium 4 — NumPy zaawansowane
**Autor:**  Magda Król 

In [1]:
import numpy as np

### Ćwiczenie 1: Broadcasting — zastosowania biznesowe (20 min)


In [2]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99], # Produkt A
[49.99, 52.99, 47.99], # Produkt B
[14.99, 15.99, 13.99], # Produkt C
[99.99, 104.99, 94.99]]) # Produkt D
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}") # (4, 3)

Kształt macierzy: (4, 3)


In [6]:
# Zadanie 1a
nowe_ceny = ceny * 1.05
print(f"Ceny po inflacji:\n {nowe_ceny}")


Ceny po inflacji:
 [[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


In [7]:
# Zadanie 1b
rabaty = np.array([0.10, 0.05, 0.15])
ceny_po_rabacie = ceny * (1 - rabaty)
print(f"Ceny po zastosowaniu rabatów dla poszczególnych sklepów:\n {ceny_po_rabacie}")

Ceny po zastosowaniu rabatów dla poszczególnych sklepów:
 [[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


In [8]:
# Zadanie 1c
marza = np.array([
    [0.30], # Produkt A: 30%
    [0.40], # Produkt B: 40%
    [0.25], # Produkt C: 25%
    [0.50]  # Produkt D: 50%
])
koszt_zakupu = ceny / (1 + marza)
print(f"Koszt zakupu po odjeciu marzy dla odpowiednich produktow:\n {koszt_zakupu}")

Koszt zakupu po odjeciu marzy dla odpowiednich produktow:
 [[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


In [11]:
# Zadanie 1d
indeksy_najtanszych = ceny.argmin(axis=1)
for i, indeks in enumerate(indeksy_najtanszych):
    print(f"Produkt {produkty[i]}: {sklepy[indeks]}")


Produkt A: Online
Produkt B: Online
Produkt C: Online
Produkt D: Online


### Ćwiczenie 2: Reshape i łączenie danych (20 min)

In [13]:
# Zadanie 2a
# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Przekształć na kwartały (4 kwartały × 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


In [14]:
# Zadanie 2b
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])
# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


In [20]:
# Zadanie 2c
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
sprzedaz_macierz = sprzedaz_flat.reshape(6, 2)
srednia_sprzedaz = sprzedaz_macierz.mean(axis=1)
zmiana = sprzedaz_macierz[:, 1] - sprzedaz_macierz[:, 0]
print(f"Macierz sprzedaży:\n{sprzedaz_macierz}\nŚrednia sprzedaz dla każdego produktu:{srednia_sprzedaz}\nZmiana sprzedazy:{zmiana}")

Macierz sprzedaży:
[[100 200]
 [150 300]
 [250 180]
 [120 220]
 [170 310]
 [260 190]]
Średnia sprzedaz dla każdego produktu:[150. 225. 215. 170. 240. 225.]
Zmiana sprzedazy:[100 150 -70 100 140 -70]


In [19]:
# Zadanie 2d
wektor_sprzedazy = kwartaly.flatten()
nowy_miesiac = np.array([235])
pelne_dane = np.concatenate([wektor_sprzedazy, nowy_miesiac])
print(f"Wektor po spłaszczeniu: {wektor_sprzedazy}\nPełne dane po dodaniu 13 miesiąca: {pelne_dane}")

Wektor po spłaszczeniu: [120 135  98 142 167 189 201 178 156 143 198 221]
Pełne dane po dodaniu 13 miesiąca: [120 135  98 142 167 189 201 178 156 143 198 221 235]


### Ćwiczenie 3: Analiza danych finansowych (30 min)

In [21]:
np.random.seed(2026)
# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])
# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

In [24]:
# Zadanie 3a
srednia = pensje.mean()
mediana = np.median(pensje)
odchylenie = pensje.std()
print(f"Średnia:{srednia:.2f}zł\nMediana:{mediana:.2f}zł\nOdchylenie standardowe:{odchylenie:.2f}zł")
nazwy_np = np.array(pracownicy)
powyzej_sredniej = nazwy_np[pensje > srednia]
ponizej_mediany = nazwy_np[pensje < mediana]
print(f"Osoby zarabiające powyżej średniej:{powyzej_sredniej}\nOsoby zarabiające poniżej mediany:{ponizej_mediany}")
rozstep = pensje.max() - pensje.min()
q3, q1 = np.percentile(pensje, [75, 25])
iqr = q3 - q1
print(f"Rozstep:{rozstep}zł\nRozstep międzykwartylowy:{iqr}zł")

Średnia:6425.00zł
Mediana:6050.00zł
Odchylenie standardowe:1616.90zł
Osoby zarabiające powyżej średniej:['Jan' 'Marek' 'Zofia']
Osoby zarabiające poniżej mediany:['Anna' 'Ewa' 'Piotr' 'Tomek']
Rozstep:4900zł
Rozstep międzykwartylowy:2200.0zł


In [28]:
# Zadanie 3b
import numpy as np
premie = np.where(oceny >= 4.5, 2000, 
                  np.where(oceny >= 4.0, 1000, 0))
nowe_wynagrodzenie = pensje + premie
indeks_max_premii = premie.argmax()
osoba_z_max_premia = pracownicy[indeks_max_premii]
print("Premie dla pracowników:")
for i in range(len(pracownicy)):
    print(f"{pracownicy[i]}: {premie[i]} zł (Ocena: {oceny[i]})")
print(f"Najwyższą premię otrzymał(a): {osoba_z_max_premia} ({premie[indeks_max_premii]} zł)")
print(f"Średnie nowe wynagrodzenie: {nowe_wynagrodzenie.mean():.2f} zł")


Premie dla pracowników:
Anna: 1000 zł (Ocena: 4.2)
Jan: 0 zł (Ocena: 3.8)
Ewa: 2000 zł (Ocena: 4.5)
Marek: 1000 zł (Ocena: 4.0)
Kasia: 2000 zł (Ocena: 4.7)
Piotr: 0 zł (Ocena: 3.5)
Zofia: 1000 zł (Ocena: 4.3)
Tomek: 0 zł (Ocena: 3.9)
Najwyższą premię otrzymał(a): Ewa (2000 zł)
Średnie nowe wynagrodzenie: 7300.00 zł


In [30]:
# Zadanie 3c
import numpy as np
indeksy_rosnaco = np.argsort(pensje)
kolejnosc = indeksy_rosnaco[::-1]
print(f"{'Poz.':<5} | {'Imię':<8} | {'Pensja':<10}| {'Staż':<5}")
for i, idx in enumerate(kolejnosc, 1):
    print(f"{i:<5} | {pracownicy[idx]:<8} | {pensje[idx]:>6} zł | {staz[idx]:>2} lat")

Poz.  | Imię     | Pensja    | Staż 
1     | Marek    |   9100 zł | 15 lat
2     | Zofia    |   8500 zł | 12 lat
3     | Jan      |   7200 zł |  8 lat
4     | Kasia    |   6300 zł |  5 lat
5     | Tomek    |   5800 zł |  4 lat
6     | Anna     |   5500 zł |  3 lat
7     | Ewa      |   4800 zł |  2 lat
8     | Piotr    |   4200 zł |  1 lat


In [35]:
# Zadanie 3d
import numpy as np
kor_staz_pensja = np.corrcoef(staz, pensje)[0, 1]
kor_staz_ocena = np.corrcoef(staz, oceny)[0, 1]
sila_pensja = abs(kor_staz_pensja)
sila_ocena = abs(kor_staz_ocena)
print(f"Korelacja Straż vs Pensja: {kor_staz_pensja:.4f}\nKorelacja Straż vs Ocena: {kor_staz_ocena:.4f}")
print("\nKtóry związek jest silniejszy:")
if sila_pensja > sila_ocena:
    print("Związek między stażem a pensją.")
else:
    print("Związek między stażem a oceną pracowniczą.")

Korelacja Straż vs Pensja: 0.9879
Korelacja Straż vs Ocena: 0.0420

Który związek jest silniejszy:
Związek między stażem a pensją.


In [36]:
# Zadanie 3e
import numpy as np
ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol
suma_per_produkt = przychod.sum(axis=1)
najlepszy_prod_idx = suma_per_produkt.argmax()
suma_per_miesiac = przychod.sum(axis=0)
najlepszy_msc_idx = suma_per_miesiac.argmax()
przychod_I_polowa = przychod[:, :3].sum()
przychod_II_polowa = przychod[:, 3:].sum()
print("Macierz przychodów (4x6):\n", przychod)
print(f"Najlepszy produkt: {produkty_nazwy[najlepszy_prod_idx]} (Przychód: {suma_per_produkt[najlepszy_prod_idx]} zł)")
print(f"Najlepszy miesiąc (indeks): {najlepszy_msc_idx} (Suma: {suma_per_miesiac[najlepszy_msc_idx]} zł)")
print(f"Suma I kwartał (m-ce 0-2): {przychod_I_polowa} zł")
print(f"Suma II kwartał (m-ce 3-5): {przychod_II_polowa} zł")
print(f"Trend: {'Wzrostowy' if przychod_II_polowa > przychod_I_polowa else 'Spadkowy'}")

Macierz przychodów (4x6):
 [[ 73500 539000 161000 339500 339500 171500]
 [244800 316800 358200  86400 270000  84600]
 [ 67500 290000 387500 327500 420000 452500]
 [ 10200   8700   6750  13200  19800  12000]]
Najlepszy produkt: Smartfon (Przychód: 1945000 zł)
Najlepszy miesiąc (indeks): 1 (Suma: 1154500 zł)
Suma I kwartał (m-ce 0-2): 2463950 zł
Suma II kwartał (m-ce 3-5): 2536500 zł
Trend: Wzrostowy


In [37]:
import numpy as np
np.random.seed(42)
wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)
print(f"{'Klient':<8} | {'Wiek':<5} | {'Wydatki':<10} | {'Wizyty':<5}")
for i in range(5):
    print(f"{i+1:<8} | {wiek[i]:<5} | {wydatki[i]:>7.2f} zł | {wizyty[i]:>5}")
print("\nPodstawowe statystyki wygenerowanej grupy:")
print(f"Średni wiek: {wiek.mean():.1f}")
print(f"Średnie wydatki: {wydatki.mean():.2f} zł")
print(f"Max wizyt: {wizyty.max()}")

Klient   | Wiek  | Wydatki    | Wizyty
1        | 39    |  216.93 zł |    11
2        | 33    |  415.87 zł |     7
3        | 41    |  431.46 zł |     3
4        | 50    |  339.54 zł |     2
5        | 32    |  467.74 zł |     3

Podstawowe statystyki wygenerowanej grupy:
Średni wiek: 33.6
Średnie wydatki: 504.46 zł
Max wizyt: 11


In [38]:
import numpy as np
print("--- STATYSTYKI OPISOWE ---")
print(f"Wiek     - Średnia: {wiek.mean():.1f}, Mediana: {np.median(wiek):.1f}, Std: {wiek.std():.1f}")
print(f"Wydatki  - Średnia: {wydatki.mean():.2f}, Mediana: {np.median(wydatki):.2f}, Std: {wydatki.std():.2f}")
print(f"Wizyty   - Średnia: {wizyty.mean():.1f}, Max: {wizyty.max()}, Min: {wizyty.min()}")
kor_wiek_wydatki = np.corrcoef(wiek, wydatki)[0, 1]
kor_wizyty_wydatki = np.corrcoef(wizyty, wydatki)[0, 1]
print("\n--- ANALIZA ZWIĄZKÓW (KORELACJA) ---")
print(f"Wiek vs Wydatki: {kor_wiek_wydatki:.3f}")
print(f"Wizyty vs Wydatki: {kor_wizyty_wydatki:.3f}")
sr = wydatki.mean()
sd = wydatki.std()
segmenty = np.where(wydatki > sr + sd, 'WYSOKI', 
                   np.where(wydatki < sr - sd, 'NISKI', 'ŚREDNI'))
nazwy_segmentow, liczebnosc = np.unique(segmenty, return_counts=True)
print("\n--- WYNIKI SEGMENTACJI ---")
for nazwa, ile in zip(nazwy_segmentow, liczebnosc):
    print(f"Segment {nazwa}: {ile} klientów")
print(f"\nŚredni wiek klientów o wysokich wydatkach: {wiek[segmenty == 'WYSOKI'].mean():.1f} lat")


--- STATYSTYKI OPISOWE ---
Wiek     - Średnia: 33.6, Mediana: 33.0, Std: 8.6
Wydatki  - Średnia: 504.46, Mediana: 516.82, Std: 189.78
Wizyty   - Średnia: 4.9, Max: 11, Min: 1

--- ANALIZA ZWIĄZKÓW (KORELACJA) ---
Wiek vs Wydatki: -0.120
Wizyty vs Wydatki: -0.159

--- WYNIKI SEGMENTACJI ---
Segment NISKI: 17 klientów
Segment WYSOKI: 12 klientów
Segment ŚREDNI: 71 klientów

Średni wiek klientów o wysokich wydatkach: 30.5 lat
