# Laboratorium 3 — NumPy
**Autor:**  Magda Król 

#### Ćwiczenie 1: Tworzenie tablic (20 min)

In [1]:
import numpy as np

In [2]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [3]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [6]:
# 5. 7 równomiernych punktów od 0 do 1
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")

Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [7]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [8]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


#### Ćwiczenie 2: Indeksowanie i slicing (20 min)

In [9]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy: 0 1 2 3 4 5 6 7 8 9 10 11
# Miesiące: Sty Lut Mar Kwi Maj Cze Lip Sie Wrz Paź Lis Gru
print(f"sprzedaz w styczniu: {miesiace_sprzedaz[0]}")

sprzedaz w styczniu: 120


In [15]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy: 0 1 2 3 4 5 6 7 8 9 10 11
# Miesiące: Sty Lut Mar Kwi Maj Cze Lip Sie Wrz Paź Lis Gru
print(f"sprzedaz w grudniu: {miesiace_sprzedaz[-1]}")

sprzedaz w grudniu: 221


In [11]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy: 0 1 2 3 4 5 6 7 8 9 10 11
# Miesiące: Sty Lut Mar Kwi Maj Cze Lip Sie Wrz Paź Lis Gru
print(f"sprzedaz w q1: {miesiace_sprzedaz[0:3]}")

sprzedaz w q1: [120 135  98]


In [12]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy: 0 1 2 3 4 5 6 7 8 9 10 11
# Miesiące: Sty Lut Mar Kwi Maj Cze Lip Sie Wrz Paź Lis Gru
print(f"sprzedaz w q4: {miesiace_sprzedaz[-3:]}")

sprzedaz w q4: [143 198 221]


In [13]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy: 0 1 2 3 4 5 6 7 8 9 10 11
# Miesiące: Sty Lut Mar Kwi Maj Cze Lip Sie Wrz Paź Lis Gru
print(f"sprzedaz co drugi miesiac: {miesiace_sprzedaz[::2]}")

sprzedaz co drugi miesiac: [120  98 167 201 156 198]


In [14]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy: 0 1 2 3 4 5 6 7 8 9 10 11
# Miesiące: Sty Lut Mar Kwi Maj Cze Lip Sie Wrz Paź Lis Gru
print(f"sprzedaz od tylu: {miesiace_sprzedaz[::-1]}")

sprzedaz od tylu: [221 198 143 156 178 201 189 167 142  98 135 120]


#### Część B — Macierz 2D

In [16]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']
print(dane[0,1])

145


In [17]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']
print(dane[2,:])

[234 267 289]


In [18]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']
print(dane[:,0])

[120  89 234  56]


In [23]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']
print(dane[1:3, 1:3])


[[102  95]
 [267 289]]


#### Ćwiczenie 3: Operacje wektorowe — analiza biznesowa (25min)

In [24]:
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])


In [26]:
print(ceny.mean())


1171.0


In [27]:
print(ceny.max())

3499


In [28]:
print(ceny.min())

89


In [34]:
nazwy = np.array(nazwy)
print(f"najdrozszy produkt: {nazwy[ceny.argmax()]}")

najdrozszy produkt: Laptop


In [35]:
nazwy = np.array(nazwy)
print(f"najtanszy produkt: {nazwy[ceny.argmin()]}")

najtanszy produkt: Ładowarka


In [37]:
wartosc_produktow = ceny * ilosci_magazyn 
for nazwa, wartosc_produktu in zip(nazwy, wartosc_produktow):
    print(f"{nazwa} łacznie: {wartosc_produktu}zł")
print(f"wartosc magazynu: {np.sum(ceny * ilosci_magazyn)}zł")

Laptop łacznie: 52485zł
Tablet łacznie: 79758zł
Smartfon łacznie: 194922zł
Słuchawki łacznie: 54444zł
Ładowarka łacznie: 27768zł
Klawiatura łacznie: 22161zł
Mysz łacznie: 25929zł
Monitor łacznie: 34477zł
Kamera łacznie: 26955zł
Drukarka łacznie: 30566zł
wartosc magazynu: 549465zł


In [39]:
nazwy = np.array(nazwy)
promocja_swiateczna = ceny * 0.85
for nazwa, promocja in zip(nazwy, promocja_swiateczna):
    print(f"{nazwa}: {promocja:.2f}zł")

Laptop: 2974.15zł
Tablet: 1614.15zł
Smartfon: 2124.15zł
Słuchawki: 296.65zł
Ładowarka: 75.65zł
Klawiatura: 211.65zł
Mysz: 109.65zł
Monitor: 1274.15zł
Kamera: 509.15zł
Drukarka: 764.15zł


In [40]:
nazwy = np.array(nazwy)
po_vat = ceny * 1.23
for nazwa, vat in zip(nazwy, po_vat):
    print(f"{nazwa}: {vat:.2f}zł")

Laptop: 4303.77zł
Tablet: 2335.77zł
Smartfon: 3073.77zł
Słuchawki: 429.27zł
Ładowarka: 109.47zł
Klawiatura: 306.27zł
Mysz: 158.67zł
Monitor: 1843.77zł
Kamera: 736.77zł
Drukarka: 1105.77zł


In [44]:
print(f"ilosc powyzej 1000: {(ceny > 1000).sum()}")


ilosc powyzej 1000: 4


In [45]:
maska = oceny_klientow >= 4.5
nazwy_wybrane = nazwy[maska]
ceny_wybrane = ceny[maska]
for nazwa, cena in zip(nazwy_wybrane, ceny_wybrane):
    print(f"{nazwa}: {cena}zł")


Laptop: 3499zł
Smartfon: 2499zł
Słuchawki: 349zł
Monitor: 1499zł


In [49]:
maska = ceny < 200
nazwy_wybrane = nazwy[maska]
ceny_wybrane = ceny[maska]
ilosci_wybrane = ilosci_magazyn[maska]
for nazwa, cena, ilosc in zip(nazwy_wybrane, ceny_wybrane, ilosci_wybrane):
    print(f"{nazwa}: {ilosc}szt, {cena}zł")

Ładowarka: 312szt, 89zł
Mysz: 201szt, 129zł


In [59]:
maska = ilosci_magazyn < 30
nazwy_wybrane = nazwy[maska]
ilosci_wybrane = ilosci_magazyn[maska]
for nazwa, ilosc in zip(nazwy_wybrane, ilosci_wybrane):
    print(f"{nazwa}: {ilosc}szt.")

Laptop: 15szt.
Monitor: 23szt.


In [62]:
ceny_niski_stan = ceny[maska]
print(ceny_niski_stan)
print(f"Łączna wartość tych produktów: {(ilosci_wybrane * ceny_niski_stan).sum()}")

[3499 1499]
Łączna wartość tych produktów: 86962


In [65]:
caly_magazyn = (ceny * ilosci_magazyn).sum()
procent_magazynu = ((ilosci_wybrane * ceny_niski_stan).sum()/caly_magazyn)*100
print(f"Ile % watrosci całego magazynu: {procent_magazynu: .2f}%")

Ile % watrosci całego magazynu:  15.83%


In [66]:
nakaz_1 = oceny_klientow >= 4.5
nakaz_2 = ceny < 1000
wynik = nazwy[nakaz_1 & nakaz_2]
print(wynik)

['Słuchawki']


In [67]:
sr_wieksza = oceny_klientow >= 4.0
sr_mniejsza = oceny_klientow < 4.0
wynik_mniejsza = ceny[sr_mniejsza].mean()
wynik_wieksza = ceny[sr_wieksza].mean()
print(f"Średnia cena przy ocenie >=4.0 vs <4.0: {wynik_wieksza:.2f}zł , {wynik_mniejsza:.2f}zł")

Średnia cena przy ocenie >=4.0 vs <4.0: 1446.14zł , 529.00zł


In [ ]:
# Przygotowanie danych
import time
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)


In [70]:
# Test 1: Pomnóż przez 2
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 241.9 ms
NumPy: 3.7 ms
NumPy jest 65× szybszy!


In [71]:
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista: 12.8 ms
NumPy: 2.6 ms
NumPy jest 5× szybszy!


In [72]:
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 174.1 ms
NumPy: 6.0 ms
NumPy jest 29× szybszy!
